### ISSUE TITLE
log2zram syntax error on line 91

### ISSUE THREAD

**Issue by skidau** [StuartIanNaylor/log2zram#1]
Getting an error when the service starts up:

Mar 26 23:50:29 raspberrypi log2zram[1111]: /usr/local/bin/log2zram/log2zram: line 91: syntax error near unexpected token `)'

Getting the same error trying to execute prune: sudo sh /usr/local/bin/log2zram/log2zram prune

/usr/local/bin/log2zram/log2zram: 91: /usr/local/bin/log2zram/log2zram: Syntax error: ")" unexpected (expecting ";;")

zramdrive and zram-swap-config seem to work fine.

**Comment by StuartIanNaylor** [comment]
Give that a whirl doh as added that after and forgot the terminator ;;

**Comment by skidau** [comment]
Works fine now. Thanks

**Comment by StuartIanNaylor** [comment]
Cheers apols those 2 are just ancillary routines if you want to take manual control.
I copied and pasted them from any older version and obs missed ;;
Apols as never tested as presumed even I could get that right :)
